language: php
php:
  - '7.1'
sudo: required
services:
  - docker
  - mongodb
  - mysql
  - memcached
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  directories:
    - $HOME/docker
    #- QM-Docker
    - $HOME/.composer/cache
env:
  global:
    - TEST_SUITE=Analytics
  matrix:
    #- HUGO_VERSION=0.20.2 # Maybe use this for documentation at some point
    - PHP_VERSION=7.1 BUILD_SERVICE="msyql workspace mongo"
# Installing a newer Docker version
before_install:
  - mysql -e 'CREATE DATABASE quantimodo_test;'
  # Load cached docker images
  #- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  #- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  #- sudo apt-get update
  #- sudo apt-get -y install docker-ce
  #- docker version
  - chmod +x ./*.sh

before_script:
  - pecl channel-update pecl.php.net
  - pecl -q install mongodb
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  #- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - ./travis-build.sh

notifications:
  email: false
  # SHA 11c32cf5fea19f4e99cbc4f4b2037ab58cb59229