language: php
php:
  - '7.1.18'
pandoc_version: 2.0
sudo: required
services:
  - docker
  - mongodb
  - mysql
  - memcached
  - pandoc
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  directories:
    - $HOME/docker
    #- QM-Docker
    - $HOME/.composer/cache
env:
  matrix:
    #- HUGO_VERSION=0.20.2 # Maybe use this for documentation at some point
    - PHP_VERSION=7.1 BUILD_SERVICE="msyql workspace mongo"
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE quantimodo_test;'
  - sudo apt-get update
  - sudo apt-get -y install pandoc
  - chmod +x ./*.sh

before_script:
  - ./clone.sh
  - ./mark_pending_on_github.sh
  - pecl channel-update pecl.php.net
  - pecl -q install mongodb
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ./tideways.sh
  - ./xhgui.sh
  - ./composer.sh

script:
  - ./phpunit.sh

after_failure:
  - ./mark_failed_on_github.sh

after_success:
  - ./mark_succeeded_on_github.sh

notifications:
  email: false